In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5], dtype=np.int32)
print(arr)

[1 2 3 4 5]


In [7]:
print(type(arr))
print(arr.size)
print(arr.ndim)
print(arr.shape)

<class 'numpy.ndarray'>
5
1
(5,)


In [8]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)
print(arr1)
print(type(arr1))
print(arr1.size)
print(arr1.ndim)
print(arr1.shape)

[[1. 2. 3.]
 [4. 5. 6.]]
<class 'numpy.ndarray'>
6
2
(2, 3)


In [10]:
arr2 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]], dtype=np.int16)
print(arr2)
print(type(arr2))
print(arr2.size)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>
8


In [11]:
## Determine the number of dimensions, size, and shape of the array
print(arr2.ndim)

3


In [20]:
print(arr2[0:1, 0:1, 0:2])

[[[1 2]]]


In [21]:
### copy array
arr3 = arr2.copy()  
print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [22]:
arr3[1] = [[9, 10], [11, 12]]
print(arr3)

[[[ 1  2]
  [ 3  4]]

 [[ 9 10]
  [11 12]]]


In [23]:
print(arr2)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [24]:
## Filter array based on a condition
filtered_arr = arr2[arr2 > 4]
print(filtered_arr)

[5 6 7 8]


In [25]:
## Joining arrays
arr4 = np.array([[13, 14], [15, 16]])
joined_arr = np.concatenate((arr2, arr4.reshape(1, 2, 2)), axis=0)
print(joined_arr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[13 14]
  [15 16]]]


In [29]:
arr6 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr6)
print(arr6.reshape(2, 5))

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [31]:
# Iterate over array elements
arr7 = arr6.reshape(2, 5)
for element in arr7:
    print(element)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [32]:
# square root of each element
arr8 = np.sqrt(arr6)
print(arr8)

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


In [33]:
# Min and Max values in an array
print("Min value:", np.min(arr6))
print("Max value:", np.max(arr6))

Min value: 1
Max value: 10


In [34]:
# Avarage and Standard Deviation
print("Average:", np.mean(arr6))
print("Standard Deviation:", np.std(arr6))

Average: 5.5
Standard Deviation: 2.8722813232690143


In [35]:
arr = np.random.randint(1, 101, 100).reshape(10, -1)

In [37]:
print(arr.shape)

(10, 10)


In [38]:
A = np.array([1, 2, 3])

B = A * 2
print(B)

[2 4 6]


In [39]:
matrix = np.eye(4)

result = np.diagonal(matrix)

print(result)

[1. 1. 1. 1.]


In [40]:
A = np.array([10, 20, 30, 40])

mask = (A >= 20) & (A <= 30)

B = A[mask]

print(B) 

[20 30]


In [41]:
arr = np.arange(1, 10).reshape(3, 3)

result = np.trace(arr)

print(result)

15


In [42]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

result = np.cross(arr1, arr2)

print(result)

[-3  6 -3]


In [43]:
# Write a Python program using NumPy to create a 5x5 matrix filled with random integers between 1 and 100. Calculate the mean and standard deviation of the matrix and print them.
matrix = np.random.randint(1, 101, (5, 5))
mean = np.mean(matrix)
std_dev = np.std(matrix)
print("Matrix:\n", matrix)
print("Mean:", mean)
print("Standard Deviation:", std_dev)


Matrix:
 [[26 12 27 68 76]
 [72 95 67 14 43]
 [50 85 70 68 65]
 [74 24 50 54 43]
 [70 83 85  8 16]]
Mean: 53.8
Standard Deviation: 25.65618833731932


In [44]:
# Using NumPy, create a 5x5 identity matrix and add a scalar value of 5 to it. Multiply the resulting matrix with a 5x1 column vector filled with random integers between 1 and 10. Print the resulting vector.
identity_matrix = np.eye(5)
result_matrix = identity_matrix + 5
column_vector = np.random.randint(1, 11, (5, 1))
result_vector = np.dot(result_matrix, column_vector)
print("Resulting Vector:\n", result_vector)


Resulting Vector:
 [[140.]
 [139.]
 [145.]
 [138.]
 [140.]]


In [45]:
# Write a Python program using NumPy to create two 3x3 matrices filled with random integers between 1 and 100. Compute their element-wise multiplication, and print the resulting matrix.
matrix1 = np.random.randint(1, 101, (3, 3))
matrix2 = np.random.randint(1, 101, (3, 3))
result_matrix = np.multiply(matrix1, matrix2)
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Element-wise Multiplication Result:\n", result_matrix)


Matrix 1:
 [[68  8 39]
 [42 77 78]
 [69 10  3]]
Matrix 2:
 [[69 59 37]
 [52 54 55]
 [24 60 13]]
Element-wise Multiplication Result:
 [[4692  472 1443]
 [2184 4158 4290]
 [1656  600   39]]


In [46]:
# Using NumPy, create a 1000-element array of random integers between 1 and 1000. Calculate the cumulative sum of the array and print the 10th, 100th, and 500th elements of the cumulative sum array.
arr = np.random.randint(1, 1001, 1000)
cumulative_sum = np.cumsum(arr)
print("10th element of cumulative sum:", cumulative_sum[9])
print("100th element of cumulative sum:", cumulative_sum[99])
print("500th element of cumulative sum:", cumulative_sum[499])


10th element of cumulative sum: 3847
100th element of cumulative sum: 48045
500th element of cumulative sum: 251099


In [48]:
# Write a Python program using NumPy to create a 10x10 matrix filled with random integers between 1 and 100. Find the minimum and maximum values of the matrix along with their indices.
matrix = np.random.randint(1, 101, (10, 10))
min_value = np.min(matrix)
max_value = np.max(matrix)
min_index = np.unravel_index(np.argmin(matrix), matrix.shape)
max_index = np.unravel_index(np.argmax(matrix), matrix.shape)
print("Matrix:\n", matrix)
print("Minimum Value:", min_value, "at index", min_index)
print("Maximum Value:", max_value, "at index", max_index)


Matrix:
 [[11 78 82  1 10 74 33 69 13 41]
 [70 65 21 83 48 99  2  1 52 28]
 [78 53 76 28 59 24 70 37 22 15]
 [ 1  3 64 11 71 19 64 45 83 66]
 [40 61  3 34 46 25 31 56 78 12]
 [11 45  1 57 69 53 96 79 58 18]
 [ 1  7 49 39 26 74 44 74 56 71]
 [70 90 66 66 27 96 76 66 98 81]
 [47 24 94 90 83 29  6 18 41 33]
 [23 95 68 40 26 35 93 82 33 72]]
Minimum Value: 1 at index (np.int64(0), np.int64(3))
Maximum Value: 99 at index (np.int64(1), np.int64(5))


In [49]:
# Write a Python program using NumPy to create a 5x5 matrix filled with random floats between 0 and 1. Replace the maximum value in the matrix with 0 and print the original and modified matrices.

matrix = np.random.rand(5, 5)
print("Original Matrix:\n", matrix)
max_value = np.max(matrix)
max_index = np.unravel_index(np.argmax(matrix), matrix.shape)
matrix[max_index] = 0
print("Modified Matrix:\n", matrix)


Original Matrix:
 [[0.62277514 0.73991467 0.96306531 0.13184559 0.3102649 ]
 [0.06317384 0.28129243 0.2150545  0.68513407 0.94501032]
 [0.66356921 0.94270978 0.14577736 0.06783284 0.78829925]
 [0.35843188 0.87790728 0.28697303 0.11275828 0.03757344]
 [0.21804928 0.80827419 0.18466956 0.12016702 0.74119252]]
Modified Matrix:
 [[0.62277514 0.73991467 0.         0.13184559 0.3102649 ]
 [0.06317384 0.28129243 0.2150545  0.68513407 0.94501032]
 [0.66356921 0.94270978 0.14577736 0.06783284 0.78829925]
 [0.35843188 0.87790728 0.28697303 0.11275828 0.03757344]
 [0.21804928 0.80827419 0.18466956 0.12016702 0.74119252]]


In [50]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

B = A[1:3, 0:2]



B[0, 0] = 100

print(A)

[[  1   2   3]
 [100   5   6]
 [  7   8   9]]


In [51]:
# Write a Python program using NumPy to create a 1D array of 20 elements with random integers between 1 and 100. Calculate the number of even and odd elements in the array and print the result.

arr = np.random.randint(1, 101, 20)
even_count = np.sum(arr % 2 == 0)
odd_count = np.sum(arr % 2 != 0)
print("Array:", arr)
print("Number of even elements:", even_count)
print("Number of odd elements:", odd_count)


Array: [65 45 48 60 45 50 44 19  9 85 34 19  3 13 23 84 61 79 85 68]
Number of even elements: 7
Number of odd elements: 13


In [52]:
A = np.arange(1, 17).reshape(4, 4)

B = A[:, ::-1]



print(B)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [53]:
# Write a Python program using NumPy to create a 2D array of size 8x8, where the outer border elements are set to 1 and the inner elements are set to 0. Print the resulting array.
arr = np.ones((8, 8), dtype=int)
arr[1:-1, 1:-1] = 0
print(arr)

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]
